- .gitignore
- influxdb_client_3/__init__.py
Added `**kwargs` to Client creation and write options. This allows users to interact with other options of the underlining client. 
Possible use case (writing pandas df to influxdb):
```python
import influxdb_client_3 as InfluxDBClient3
import pandas as pd
import numpy as np
client = InfluxDBClient3.InfluxDBClient3(token="spqIiWojlcbAQC-FotEltyPqKhlhppuo36DYc5RIXxZl3EM3nRvSDQ3Lc75tkjBlml__oG3bI199gG3IdVKYlw==",
host="eu-central-1-1.aws.cloud2.influxdata.com",
org="6a841c0c08328fb1",
namespace="test")
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
dates = pd.date_range(start='2023-03-01', end='2023-03-29', freq='5min')
df = pd.DataFrame(np.random.randn(len(dates), 3), index=dates, columns=['Column 1', 'Column 2', 'Column 3'])
df['tagkey'] = 'Hello World'
print(df)
client.write(df, …
```
> Updated write API to support pandas df ingest

- README.md
- Update sql output example (markdown).
- Remove unnecessary terminal prompts (`%`) to avoid user copy-pasting them.
- Explain interactive prompts and separate commands from output.
- Fix typo.
> fix: CLI examples and instructions

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
- .github/ISSUE_TEMPLATE/SUPPORT.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/semantic.yml
- .gitignore
- README.md
- setup.py
- tests/test_influxdb_client_3.py
This PR introduce support for CI integration (next PRs will enable code style checks) add templates for GitHub issues, ...
> chore: improve GitHub integration, add CI config

- CHANGELOG.md
- influxdb_client_3/write_client/client/write/dataframe_serializer.py
- tests/test_dataframe_serializer.py
Closes #76 
Use pandas to decide what is `NaN` to allow us to have nullable bools, ints and strings.
With a real world dataset, 10_000 lines, 156 columns
1.86 s ± 26.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.7 s ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.51 s ± 25.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> fix: Support using pandas nullable types

- .circleci/config.yml
- .flake8
- CHANGELOG.md
- Examples/batching_example.py
- Examples/cloud_dedicated_query.py
- Examples/community/custom_url.py
- Examples/community/database_transfer.py
- Examples/file-import/csv_write.py
- Examples/file-import/feather_write.py
- Examples/file-import/json_write.py
- Examples/file-import/orc_write.py
- Examples/file-import/parquet_write.py
- Examples/file-import/write_file_parse_options.py
- Examples/flight_options_example.py
- Examples/pokemon-trainer/basic-query.py
- Examples/pokemon-trainer/basic-write-errorhandling.py
- Examples/pokemon-trainer/basic-write-writeoptions.py
- Examples/pokemon-trainer/basic-write.py
- Examples/pokemon-trainer/pandas-write.py
- Examples/pokemon-trainer/write-batching-flight-calloptions.py
- Examples/pokemon-trainer/write-batching.py
- Examples/query_type.py
- influxdb_client_3/__init__.py
- influxdb_client_3/read_file.py
- influxdb_client_3/write_client/_sync/api_client.py
- influxdb_client_3/write_client/client/_base.py
- influxdb_client_3/write_client/client/influxdb_client.py
- influxdb_client_3/write_client/client/write/dataframe_serializer.py
- influxdb_client_3/write_client/client/write_api.py
- tests/test_influxdb_client_3.py
This PR enable CI check for source file code style checking.
> fix: code style of source files

- CHANGELOG.md
- Examples/batching_example.py
- Examples/community/custom_url.py
- Examples/community/database_transfer.py
- Examples/file-import/csv_write.py
- Examples/file-import/feather_write.py
- Examples/file-import/json_write.py
- Examples/file-import/orc_write.py
- Examples/file-import/parquet_write.py
- Examples/file-import/write_file_parse_options.py
- Examples/pokemon-trainer/cookbook.ipynb
- Examples/pokemon-trainer/write-batching-flight-calloptions.py
- Examples/pokemon-trainer/write-batching.py
- README.md
WriteOptions is the object, but the parameter is expected to be write_options.
fixes: #79
> fix: Use correct write_options parameter in examples

- .circleci/config.yml
- .markdownlint.yml
- CHANGELOG.md
- influxdb_client_3/__init__.py
- pytest.ini
- setup.py
- tests/test_deep_merge.py
- tests/test_influxdb_client_3_integration.py
- tests/test_merge_options.py
- tests/test_query.py
1. Added support for named query parameters:
```python
from influxdb_client_3 import InfluxDBClient3
with InfluxDBClient3(host="https://us-east-1-1.aws.cloud2.influxdata.com",
token="my-token",
database="my-database") as client:
table = client.query("select * from cpu where host=$host", query_parameters={"host": "server01"})
print(table.to_pandas())
```
2. Added simple write-query integration tests
> feat: query parameters

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- influxdb_client_3/write_client/client/util/date_utils.py
- tests/test_date_helper.py
- tests/test_merge_options.py
- tests/test_query.py
Use build-in date parsing feature. From version 3.11 the performance is same as for ciso8601.
For more info see - https://github.com/influxdata/influxdb-client-python/pull/657
https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat
> feat: use build-in Python parsing feature for python >= 3.11

- CHANGELOG.md
- influxdb_client_3/write_client/client/write/point.py
- tests/test_point.py
> refactor: to `timezone` specific `datetime` helpers to avoid use deprecated functions

- influxdb_client_3/__init__.py
- influxdb_client_3/query/query_api.py
- pytest.ini
- tests/test_influxdb_client_3.py
- tests/test_influxdb_client_3_integration.py
- tests/test_query.py
Extracts Query API from the client core in a way similar to Write API. Does not change client public API. The motivation is easier/better maintenance and extending in the future.
> chore: refactor init and extract Query API

- CHANGELOG.md
- influxdb_client_3/query/__init__.py
Closes #97 
Added missing module declaration for Query module.
```console
mkdir missing_module
cd missing_module
python -m venv ./.venv  
source .venv/bin/activate
pip install git+https://github.com/InfluxCommunity/influxdb3-python@query-package
python -c 'from influxdb_client_3 import InfluxDBClient3, Point'
```
> fix: missing module declaration

- CHANGELOG.md
- influxdb_client_3/write_client/client/write/dataframe_serializer.py
- influxdb_client_3/write_client/client/write/polars_dataframe_serializer.py
- tests/test_dataframe_serializer.py
Fixes https://github.com/influxdata/EAR/issues/5299
`np.inf` and `-np.inf` values in a Pandas data frame are skipped during during serialization into line protocol.
Other fixes:
* replace `polars.DataFrame.apply` (deprecated, and does not exists in latest version) with `polars.DataFrame.map_rows`
* replace pandas data frame `replace()` with `apply(lambda: )` to avoid future problems
```
dataframe_serializer.py:250: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
For example, when doing 'df[col].method(value, inplace=True)', try using …
```
> fix: skip infinite values during serialization

- CHANGELOG.md
- influxdb_client_3/write_client/client/exceptions.py
- tests/test_api_client.py
Extends error response processing to handle Edge (OSS) errors as well. It sets `InfluxDBError.message` value from either `message` (Cloud) or `data.error_message` / `error` (Edge) element value in the response body when an error occurs.
> fix: handle Edge errors

- CHANGELOG.md
- README.md
- influxdb_client_3/__init__.py
- influxdb_client_3/write_client/client/_base.py
- influxdb_client_3/write_client/client/influxdb_client.py
- tests/test_influxdb_client_3.py
- tests/test_influxdb_client_3_integration.py
Adds `auth_scheme` keyword argument to `InfluxDBClient` initialization to allow setting other token authentication scheme other then the default `"Token"` (used for Cloud). For Edge (OSS), users need to set it to `"Bearer"`.
> fix: Edge authentication support

- CHANGELOG.md
- influxdb_client_3/write_client/client/_base.py
- tests/test_polars.py
Closes #104
Fixed import of the `PolarsDataframeSerializer`.
> fix: import PolarsDataframeSerializer

- CHANGELOG.md
- Examples/__init__.py
- Examples/cloud_dedicated_query.py
- Examples/cloud_dedicated_write.py
- Examples/config.py
- Examples/handle_http_error.py
- influxdb_client_3/write_client/client/exceptions.py
- tests/test_api_client.py
- tests/test_influxdb_client_3_integration.py
- add helper method to get response headers in `InfluxDBError`
- add tests of this new functionality
- in examples add `config.py` with Config class to centralize resolution of environment variables usable in examples
- fix `cloud_dedicated_write.py` which used outdated import of `write_options`
- add example of working with response header values on write
> feat: expose response headers in InfluxDBError

- CHANGELOG.md
- influxdb_client_3/write_client/client/write_api.py
Closes #110
- Change logging level after disposal of batching processor to DEBUG.
> fix: #110 - set message 'processor was disposed' to level debug.

- CHANGELOG.md
- setup.py
Fixed adding py.typed into package.
Tested via:
```
mkdir typed
cd typed
python -m venv venv
. venv/bin/activate
python -m pip install git+https://github.com/InfluxCommunity/influxdb3-python.git@typed-definition-setup.py
ls -l venv/lib/python3.11/site-packages/influxdb_client_3/
```
> fix: add py.typed to the package definition

- CHANGELOG.md
- influxdb_client_3/write_client/client/write_api.py
- tests/test_polars.py
Closes #
N/A
Fixed import error of "PolarsDataframeSerializer" in "write_api.py"
> fix: write polars dataframe

- .circleci/config.yml
- CHANGELOG.md
- influxdb_client_3/__init__.py
- influxdb_client_3/query/query_api.py
- tests/test_query.py
Closes #118
* extract proxy argument when creating _query_api and use it as new field for `QueryApi` object
* Use this object to set generic Flight client options
> fix: 118 - query not using proxy

- CHANGELOG.md
- Examples/query_async.py
- influxdb_client_3/__init__.py
- influxdb_client_3/query/query_api.py
- tests/test_influxdb_client_3.py
- tests/test_influxdb_client_3_integration.py
- tests/test_query.py
- tests/util/__init__.py
- tests/util/mocks.py
Closes #
* add `query_async` method to `query_api`
* move query ticket preparation statements to reusable methods in `query_api`
* in `query_async` method wrap call to `FlightClient.doGet` in current event loop retrieved from `asyncio`
* in `query_async` method wrap `FlightStreamReader` translations in same event loop
* unit tests of changes to `query_api`
* in `InfluxDBClient3` expose these changes with new `query_async` method
* unit and integration tests of changes to `InfluxDBClient3`
* refactor flight server mocks and test utility functions to `tests/util`
* in `query_api.__init__()` improve merge of `_flight_client_options` so that some values do not get dropped or overwritten
> feat: asynchronous query

- CHANGELOG.md
- Examples/basic_ssl_example.py
- Examples/batching_example.py
- Examples/cloud_dedicated_query.py
- Examples/cloud_dedicated_write.py
- Examples/community/custom_url.py
- Examples/community/database_transfer.py
- Examples/config.py
- Examples/file-import/csv_write.py
- Examples/file-import/feather_write.py
- Examples/file-import/json_write.py
- Examples/file-import/orc_write.py
- Examples/file-import/parquet_write.py
- Examples/file-import/write_file_parse_options.py
- Examples/flight_options_example.py
- Examples/handle_http_error.py
- Examples/pandas_write.py
- Examples/pokemon-trainer/basic-query.py
- Examples/pokemon-trainer/basic-write-errorhandling.py
- Examples/pokemon-trainer/basic-write-writeoptions.py
- Examples/pokemon-trainer/basic-write.py
- Examples/pokemon-trainer/cookbook.ipynb
- Examples/pokemon-trainer/pandas-write.py
- Examples/pokemon-trainer/write-batching-flight-calloptions.py
- Examples/pokemon-trainer/write-batching.py
- Examples/query_async.py
- Examples/query_type.py
- README.md
- influxdb_client_3/query/query_api.py
- influxdb_client_3/write_client/client/influxdb_client.py
Closes [Issue](https://github.com/InfluxCommunity/influxdb3-python/issues/128)
- Remove org parameters from examples and Readme because It is not mandatory in Influxdb3
> feat: remove org from examples code

- CHANGELOG.md
- influxdb_client_3/__init__.py
- influxdb_client_3/write_client/_sync/api_client.py
- influxdb_client_3/write_client/client/_base.py
- influxdb_client_3/write_client/client/influxdb_client.py
- influxdb_client_3/write_client/configuration.py
- tests/test_api_client.py
- tests/test_influxdb_client_3.py
Closes #
_Briefly describe your proposed changes:_
> feat: support gzip threshold

- README.md
Add a basic "contributing" section to help community developers get tests running more readily.
**Note:** tests and changelog not applicable.
> docs(README.md): add basic contributing guide

- CHANGELOG.md
- pyproject.toml
- setup.py
Issue link [#695](https://github.com/influxdata/influxdb-client-python/issues/695)
- Move the "setuptools" package to build dependency to accommodate new check from the homeassistant library
_ Before the fix
_ After the fix: I think the new error message means we have had solved the dependency issue, check out "home-assistant-core/script/hassfest/requirements.py" line 169. The new error message is for the homeassistant team
_ My steps to reproduce the issue:
- Checkout [Home assistant core repo](https://github.com/home-assistant/core)
-  Run "source venv/bin/activate"
- Run "python3 -m script.gen_requirements_all && pip3.13 install -r requirements_all.txt"
- Run "python3 -m script.hassfest --integration-path "home-assistant-core/homeassistant/components/influxdb" --requirement"
- My steps …
> feat: move setup tools to build dependency

- .circleci/config.yml
- CHANGELOG.md
Closes #
- [Changes](https://github.com/InfluxCommunity/influxdb3-java/pull/266).
> feat: support arm64 circleci
